### PR TITLE
Preserve 3.3.x method signature

### PR DESCRIPTION
**Pull request by mches**
Restores a 3.3.x method signature to preserve compatibility with the current version of Spotless

### CODE REVIEW

**Comment by Ekryd** [comment]
🤔 Do you need this? Can't you use an earlier version of SortPom until the method can be migrated?

**Comment by mches** [comment]
If this were merged and released I could upgrade to the latest version and remove workarounds, but it's not as though I'm stuck. I can appreciate why you wouldn't want to go to the trouble when we know the eventual Spotless release will alleviate the problem.

**Comment by Ekryd** [comment]
FYI, some sidetracking. I was delaying a new major version for this PR: https://github.com/Ekryd/sortpom/pull/429
I thought that I wanted to change both the schemaLocation setting and the spaces at the same time. Feel free to check it out

**Comment by mches** [comment]
I had a look and that should work. I don't think I would use indentAttributes=all myself. I find myself wanting to break and indent _properties_ with long names or values, like sonar properties. I'm achieving that right now with regex replacement.

**Pull request closed without merging**
