### PR TITLE
Addition to sort 'modules' section alphabetically.

### PR DESCRIPTION
**Pull request by msbg**
Hi, 
Many thanks for creating this plugin, greatly appreciated. One small extra feature I would like is to be able to sort the 'modules' section of a pom alphabetically(which is very handy in large multi-module builds). I've put together an update here that will optionally enable this. Any thoughts/updates appreciated.

Regards,

- monica

### CODE REVIEW

**Comment by Ekryd** [comment]
Great job! I must admire your willingness to enter old code :-)

I see your problem and I will look into this as soon as I am able.

**Comment by msbg** [comment]
Thanks! 😊

**Comment by Ekryd** [comment]
I have reviewed your code and have found... nothing to complain about! 🥇  
Just waiting for some testing for other functionality in issue #44 before I can merge this into master and release it.

**Comment by msbg** [comment]
Thanks😊

**Comment by Ekryd** [comment]
Merged into master. Will try to release it during the weekend.
Can you please checkout master and try it out?

Also, the sorting of modules can cause potential side effects, right? If a maven build has an implicit dependency to the build order of the modules. 
I have never experienced side effects like like that myself. Have you?

**Comment by msbg** [comment]
Will do – not encountered any maven dependency issues related to build order of modules myself either!


  *   monica

**Comment by bguerin** [comment]
> sorting of modules can cause potential side effects

http://maven.apache.org/guides/mini/guide-multiple-modules.html, chapter _Reactor Sorting_

**Comment by Ekryd** [comment]
Thanks for the reference. I can use that as I document the new functionality

**Comment by msbg** [comment]
I never knew that - thanks for the info!

**Comment by Ekryd** [comment]
Released 2.8.0 just now with the new parameter 'SortModules'. Thanks for your help with the pull request! Please try it out and spread the word :-)

**Pull request merged**
