### PR TITLE
Junit jupiter and hamcrest

### PR DESCRIPTION
**Pull request by nhojpatrick**
Recreated PR https://github.com/Ekryd/sortpom/pull/72 onto nhojpatrick-junit5.

### CODE REVIEW

**Comment by Ekryd** [comment]
Thanks!!

**Comment by Ekryd** [comment]
I saw that the junit-platform-launcher was included as dependency. Was the reason IntelliJ? I run IntelliJ 2019.3 and I am able to run the unit tests anyway.

**Comment by Ekryd** [comment]
I have done a full review on the conversion to junit 5 and I am impressed! Did you use any tool to do the conversions? And how come that you decided to this? I have looked at Junit 5 a few times but haven't had the time to do the conversions myself.

**Comment by nhojpatrick** [comment]
> I saw that the junit-platform-launcher was included as dependency. Was the reason IntelliJ? I run IntelliJ 2019.3 and I am able to run the unit tests anyway.

It was an issue I had maybe 12 months ago and I found it easier to always add it and keep it. From memory it was maybe 2018.3 or 2019.1 and might have only been an issue in the EAP version, and/or with JUnit v5.3.x/5.4.x/5.5.x. Basically it didn't correct scan the see any tests, if you add launcher, then it sees the tests, but if you then removed launcher, delete test config, it then still saw tests.

**Comment by Ekryd** [comment]
> > I saw that the junit-platform-launcher was included as dependency. Was the reason IntelliJ? I run IntelliJ 2019.3 and I am able to run the unit tests anyway.
> 
> It was an issue I had maybe 12 months ago and I found it easier to always add it and keep it. From memory it was maybe 2018.3 or 2019.1 and might have only been an issue in the EAP version, and/or with JUnit v5.3.x/5.4.x/5.5.x. Basically it didn't correct scan the see any tests, if you add launcher, then it sees the tests, but if you then removed launcher, delete test config, it then still saw tests.

Hmmm, good to know. If I ever have any troubles with the tests, then I will re-include the launcher.

**Comment by nhojpatrick** [comment]
> I have done a full review on the conversion to junit 5 and I am impressed! Did you use any tool to do the conversions? And how come that you decided to this? I have looked at Junit 5 a few times but haven't had the time to do the conversions myself.

Everything converted manually;
- lots of prep tasks
- removing wild card imports
- changing everything to hamcrest
- search for @Rules and do those 1st and convert to assertThrows
- search for catch and probably covert those to assertThrows
- massive Find/Replaces for imports
- adding fake assertEquals methods, then refactoring fake assertEquals because the order where the message goes changed, then removing fake assertEquals.

The reason... sortpom is a plugin I've only recently come across and started to use everywhere I can so wanted to help out, also I want to improve my understanding and knowledge of JUnit v4 to v5 conversions.

**Comment by Ekryd** [comment]
You did a great job with the conversion and I learned about JUnit 5 just by looking at your code.

**Pull request merged**
