### PR TITLE
Adding integration tests, via the invoker plugin

### PR DESCRIPTION
**Pull request by bguerin**
While your plugin is very well covered with unit tests, these ones can served as demonstration / documentation to see how your plugin works on real cases

### CODE REVIEW

**Comment by Ekryd** [comment]
Wow! I have to look into this.

**Comment by bguerin** [comment]
If you want, you can attach jacoco to the invoker plugin execution, thus adding even more coverage :)

**Comment by Ekryd** [comment]
This is really cool! I have a few comments. 
* I see that you invoke the invoker plugin both in the maven-plugin module and also as a report plugin in the main pom, is that to publish the report if you do a 'site' build?
* I corrected the FileUtil test, that should not have been your job :-)
* Is it possible replace the groovy files with regular java files? It's no big deal, I just feel more comfortable with java.
* Could you do a a new pull request with just 1 test so that I get a feel for the test setup first. Then you could add the rest of the tests as a second pull request.
* Will I be able to test the default values for the sortpom plugin configuration with the invoker plugin? That has been impossible for me so far. (Since they are set by Maven itself)

* Finally, Thanks for the effort that you put into these tests! It is greatly appreciated!

**Comment by bguerin** [comment]
Hello

* yes for the report during site phase, it shows the different tests played, their result and the time they took. See maven.apache.org/plugins/maven-invoker-plugin/report-mojo.html
* oki, no problem
* sorry but no the plugin only support bsh and groovy http://maven.apache.org/plugins/maven-invoker-plugin/run-mojo.html#postBuildHookScript
* of course, no pb
* yes
* my pleasure, it is a nice plugin, used everyday in my compagny, so if I can help a little

**Comment by bguerin** [comment]
Do you want me to re open a PR with the integration-tests added here, but following the default one you merged (and of course following your modifications !) or you prefer to make your owns ?

**Comment by Ekryd** [comment]
I think you should do a PR. I am sure that those tests will be excellent.

**Comment by Ekryd** [comment]
I would be very pleased if you could add the tests that you prepared before.

**Comment by bguerin** [comment]
I will do it, just need a few time

**Comment by bguerin** [comment]
still working on it ... keeping you posted

**Comment by bguerin** [comment]
Rewrite done, awaiting for your review :)

**Comment by Ekryd** [comment]
Thanks buddy! I will look into it real soon

**Comment by Ekryd** [comment]
Made some changes:
Removed expected_pom in the already sorted test.
Removed the keep-blank-lines since it was already tested in four-space-indent
Thanks again for your contribution, it is much appreciated!

**Comment by bguerin** [comment]
Hello,

Ok for keep-blank-lines. But for the already sorted expected_pom, without it, how do you ensure that the pom is left unmodified at all ? From my point of view, just believing the logs is not enough...

**Comment by bguerin** [comment]
Actually, I also think that deleting the _keep-blank-lines_ test is a bad thing.

The goal of _four-spaces-indent_ is to ensure that the indentation is good, even on blank lines if they are kept (ok, I should have created another test to explicit this)

The goal of _keep-blank-lines_ is only to ensure that blank lines are kept, whatever their indentation (we should add arbitrary indentation on the original POM to explicit this)

**Comment by Ekryd** [comment]
Good point with expected. I will put that back. 
The invoker test compliment the existing tests, so I dont see a major problem that one testcase tests multiple parameters. I already have lots of tests for each parameter. 
Each invoker test adds 2 seconds to the build time, so when I saw that two were overlapping I removed one. I'm sure that my total testsuite would have been different if I had your expertise in the invoker tests from the start.

**Pull request merged**
